### ISSUE TITLE
Feature request: Firefox support

### ISSUE THREAD

**Issue by jeremyckahn** [joplin/web-app#1]
I'm very excited to see this repo!

I would like to see a Joplin web app that supports Firefox.

Thanks for your hard work on Joplin so far!

**Comment by personalizedrefrigerator** [comment]
Hi,

Work on a web client is currently being done on the main Joplin repository (see https://github.com/laurent22/joplin/pull/10650). When https://github.com/laurent22/joplin/pull/10650 is merged, this repository will be used to host a GitHub Actions workflow that deploys the web client to GitHub pages (perhaps similar to https://github.com/joplin/website).

At present, the web client supports Firefox ([demo](https://personalizedrefrigerator.github.io/joplin/web-client/)). However database access currently seems slower than in Chrome, particularly when setting up the app for the first time.

**Comment by jeremyckahn** [comment]
Ah awesome!! I'm so excited to see a proper web build of Joplin. I'll close this issue.

I appreciate your work here @personalizedrefrigerator! :pray:

**Comment by TCB13** [comment]
> However database access currently seems much slower than in Chrome

@personalizedrefrigerator ,

What type of DB is it using? I tried to check the dev tools, couldn't find anything on local storage...

**Comment by personalizedrefrigerator** [comment]
See https://joplinapp.org/help/dev/spec/web_app/:
> The web app uses [@sqlite.org/sqlite-wasm](https://github.com/sqlite/sqlite-wasm) for database access.

sqlite-wasm is configured to use OPFS is used for persistent storage.

**Comment by TCB13** [comment]
Thanks.
